language: ruby
os:
- linux
- osx
rvm:
- ruby-2.5.1
dist: trusty
before_install: gem install bundler
script:
- bundle exec rspec
- bundle exec rubocop
after_script:
- bundle exec codeclimate-test-reporter
notifications:
  email:
  - nicolasganz37+travis@gmail.com
env:
  global:
    secure: YKlnKnoP60fsjOB8GSaJ0LQ25BgW3wtMs0inBmiAJQox5e0qGvwLfpnrOdsef3ICP9XS93qKF5SjZMYfvuV+cVysXLZi94nkGMpOl8gM2xni1BFcUKCCUf9TDTrXG2QFvRglI7DRDMjgsRQfUl51/hMUfJAkvv5dESJQWPNstGOadswtVZfPchEKbGnTXClugIrp6OABqcRQzSYnF9FWf0bem9c1b/tFJZY5amFJ0INVe03LohtVJBq+psjPfRDPw87JgYTp/lWSsPEW6ZFJLgU7BeJEzDoiNr9yZIpntwlK1o/Oc5fLWR5xrJTVqKbO1skfYHSorLlOSyAERZcNq3NczroOzjvfdf+1tMzeu7N6t7cTsUbcf7LbHeIGDPTFY5L7Aywh2MN/q968UErYjtmmSABbFpddBumBZIFpVSvLl66m3XmfJOXdehUqlFymm0rRO6yH8VnLjanOsdWF6P4myNoFNQeVEMHfjvkXE3VxHb3XAkgMFVKv8eXNUs/D+31eo2+JnCnHBh11m9am+2nmByj7188ExSV61+zMYtXVM036eSfd1VhIXDIsS6/iX0Ecvd1m6oDLJWksr8/gl+/s8DPF1OfEsHb0idwfScGdou4Jn8FYAyD6+EwgajmTR1pE3Y2DiJHiLr9Fc514sMNtf9QBsGLbmDIz+1SYVvA=
