version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 25

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install --path vendor/bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec
  - bundle exec rubocop
